name: Storybook Play Tests (CI-min)

on:
  pull_request:
    branches: [main]

jobs:
  test-stories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.10.0
          run_install: false

      - name: Setup Node (from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Build Storybook
        run: pnpm run build:sb

      # If you run tests:
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Serve Storybook & Test
        run: |
          npx http-server ./storybook-static -p 6006 -s &
          echo $! > sb_pid.txt
          npx wait-on http://127.0.0.1:6006
          pnpm run test:stories
      - if: always()
        name: Stop server
        run: kill $(cat sb_pid.txt) || true
